Repository wecode-bootcamp-korea/10-laroche-cream-frontend, pull requests merged in 2020-07, with the labels that each got.

#1 [박민규] modify : nav 추가 기능구현 및 리팩토링
  package-lock.json
  package.json
  src/Components/DetailPage/DetailPage.js
  src/Components/DetailPage/DetailPage.scss
  src/Components/Nav.js
  src/Components/Nav/BodyCare.js
  src/Components/Nav/BodyCare.scss
  src/Components/Nav/HotItem.js
  src/Components/Nav/HotItem.scss
  src/Components/Nav/LogoBar.js
  src/Components/Nav/LogoBar.scss
  src/Components/Nav/MenuBar.js
  src/Components/Nav/MenuBar.scss
  src/Components/Nav/MomBaby.js
  src/Components/Nav/MomBaby.scss
  src/Components/Nav/Skin.js
  src/Components/Nav/Skin.scss
  src/Components/Nav/TopBar.js
  src/Components/Nav/TopBar.scss
  src/Components/Nav/UvCare.js
  src/Components/Nav/UvCare.scss
  src/index.js
  src/reset.scss
Labels: Status: 수정 요청

#2 [라로슈포제 이지윤] Fix: Comflict 해결 (NavBar-main)
  package-lock.json
  package.json
  public/font/LocatorWebLight.woff
  public/font/notokr-demilight.woff2
  public/mockdata/data.json
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Main/ItemBox.js
  src/Components/Main/ItemBox.scss
  src/Components/Main/Slides.js
  src/Components/Main/Slides.scss
  src/Components/Nav.scss
  src/Components/Nav/BodyCare.scss
  src/Components/Nav/HotItem.scss
  src/Components/Nav/MenuBar.scss
  src/Components/Nav/MomBaby.scss
  src/Components/Nav/Skin.scss
  src/Components/Nav/UvCare.scss
  src/Pages/Main/BestSeller/BestSeller.js
  src/Pages/Main/BestSeller/BestSeller.scss
  src/Pages/Main/BrandStoryBanner/BrandStoryBanner.js
  src/Pages/Main/BrandStoryBanner/BrandStoryBanner.scss
  src/Pages/Main/Discount/Discount.js
  src/Pages/Main/Discount/Discount.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Membership/Membership.js
  src/Pages/Main/Membership/Membership.scss
  src/Pages/Main/Notice/Notice.js
  src/Pages/Main/Notice/Notice.scss
  src/Pages/Main/OnlynHot/OnlynHot.js
  src/Pages/Main/OnlynHot/OnlynHot.scss
  src/Pages/Main/Review/Review.js
  src/Pages/Main/Review/Review.scss
  src/Pages/Main/SkinSolution/SkinSolution.js
  src/Pages/Main/SkinSolution/SkinSolution.scss
  src/Pages/Main/Suggestion/Suggestion.js
  src/Pages/Main/Suggestion/Suggestion.scss
  src/Pages/Main/TopSlideBar/TopSlideBar.js
  src/Pages/Main/TopSlideBar/TopSlideBar.scss
  src/Pages/Main/Video/Video.js
  src/Pages/Main/Video/Video.scss
  src/Pages/ProductList/Categories.js
  src/Pages/ProductList/Categories.scss
  src/Pages/ProductList/ProductList.js
  src/Routes.js
  src/common.scss
  src/index.js
Labels: Status: 리뷰 요청

#5 [라로슈포제 이지윤] Fix: Conflict 해결 (ProductList)
  public/font/LocatorWebLight.woff
  public/font/notokr-demilight.woff2
  public/index.html
  public/manifest.json
  public/mockdata/data.json
  public/mockdata/mockupdata.json
  src/Components/FloatBar/FloatBar.js
  src/Components/FloatBar/FloatBar.scss
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Main/ItemBox.js
  src/Components/Main/ItemBox.scss
  src/Components/Main/Slides.js
  src/Components/Nav/BodyCare.scss
  src/Components/Nav/LogoBar.scss
  src/Components/Nav/MenuBar.js
  src/Components/Nav/MenuBar.scss
  src/Components/Nav/MomBaby.scss
  src/Components/Nav/Skin.js
  src/Components/Nav/Skin.scss
  src/Components/Nav/TopBar.js
  src/Components/Nav/UvCare.scss
  src/Pages/Main/BestSeller/BestSeller.js
  src/Pages/Main/BrandStoryBanner/BrandStoryBanner.scss
  src/Pages/Main/OnlynHot/OnlynHot.js
  src/Pages/Main/SkinSolution/SkinSolution.js
  src/Pages/Main/SkinSolution/SkinSolution.scss
  src/Pages/Main/TopSlideBar/TopSlideBar.js
  src/Pages/Main/TopSlideBar/TopSlideBar.scss
  src/Pages/ProductList/Categories.js
  src/Pages/ProductList/Categories.scss
  src/Pages/ProductList/ItemList.js
  src/Pages/ProductList/ItemList.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Pages/ProductList/SideLeft.js
  src/Pages/ProductList/SideLeft.scss
Labels: Status: 리뷰 요청

#3 회원가입페이지
  package-lock.json
  package.json
  public/images/ico_step.webp
  public/index.html
  src/Components/Nav/TopBar.js
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Pages/SignUp/SignUpInfo.js
  src/Pages/SignUp/SignUpInfo.scss
  src/Pages/SignUp/SignUpOptionalInfo.js
  src/Pages/SignUp/SignUpOptionalInfo.scss
  src/Routes.js
  src/common.scss
Labels: Status: Accepted

#6 Feature/sign in
  .vscode/settings.json
  package-lock.json
  package.json
  src/Pages/SignIn/MemberSignIn.js
  src/Pages/SignIn/MemberSignIn.scss
  src/Pages/SignIn/NonMemberSignIn.js
  src/Pages/SignIn/NonMemberSignIn.scss
  src/Pages/SignIn/SignIn.js
  src/Pages/SignIn/SignIn.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#8 [라로슈포제 최태희] Add: input 태그를 다루는 함수작성
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUpOptionalInfo.js
  src/Pages/SignUp/SignUpOptionalInfo.scss
Labels: Status: 추가 기능 구현중

#10 [박민규 ]add : detailpage
  package-lock.json
  package.json
  public/data/data.json
  public/data/mockupdata.json
  src/Components/DetailPage.js
  src/Components/DetailPage.scss
  src/Components/DetailPage/DetailLeft/DetailLeft.js
  src/Components/DetailPage/DetailLeft/DetailLeft.scss
  src/Components/DetailPage/DetailPage.js
  src/Components/DetailPage/DetailPage.scss
  src/Components/DetailPage/DetailPageRight/DetailRight.js
  src/Components/DetailPage/DetailPageRight/DetailRight.scss
  src/Components/DetailSlider/DetailSlider.js
  src/Components/DetailSlider/DetailSlider.scss
  src/Components/DetailTab/DetailTab.js
  src/Components/DetailTab/DetailTab.scss
  src/Components/FloatBar/FloatBar.js
  src/Components/Nav/HotItem.js
  src/Components/Nav/TopBar.js
  src/Components/PayInfo/PayInfo.scss
  src/Components/PayInfo/Payinfo.js
  src/Pages/SignIn/MemberSignIn.js
  src/Pages/SignIn/MemberSignIn.scss
  src/Routes.js
  src/config.js
Labels: Status: 추가 기능 구현중

#11 [라로슈포제 이지윤] Fix: Conflict 해결
  src/Components/FloatBar/FloatBar.js
  src/Components/Main/ItemBox.scss
  src/Components/Main/LikeItemBox.js
  src/Components/Nav/LogoBar.scss
  src/Components/Nav/TopBar.js
  src/Components/Nav/TopBar.scss
  src/Pages/Cart/CartItems.js
  src/Pages/Cart/CartItems.scss
  src/Pages/Cart/ItemCard.js
  src/config.js
Labels: Status: 리뷰 요청

#13 [라로슈포제 최태희] Modify - 로그인성공시 이동경로 수정
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/SignIn/MemberSignIn.js
  src/Pages/SignIn/SignIn.js
  src/config.js
Labels: Status: Accepted

#12 Feature/sign up
  src/Components/DetailPage.scss
  src/Components/DetailPage/DetailLeft/DetailLeft.js
  src/Components/DetailSlider/DetailSlider.scss
  src/Components/DetailTab/DetailTab.js
  src/Components/DetailTab/DetailTab.scss
  src/Components/FloatBar/FloatBar.js
  src/Components/Nav/TopBar.js
  src/Pages/SignIn/SignIn.js
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Pages/SignUp/SignUpInfo.js
  src/Pages/SignUp/SignUpInfo.scss
  src/Pages/SignUp/SignUpOptionalInfo.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청
